In [37]:
import pandas as pd
dtypes = train.dtypes
basis_stats = train.describe().T
basis_stats['dtype'] = dtypes
type_stats= basis_stats.reset_index().rename(columns={'index': 'Column Name'})
type_stats

,Column Name,count,mean,std,min,25%,50%,75%,max,dtype
0,p_id,614.0,385.542345,222.135103,0.000,194.250,380.5000,583.7500,767.00,int64
1,Pregnancies,614.0,3.809446,3.375544,0.000,1.000,3.0000,6.0000,15.00,int64
2,Glucose,614.0,120.465798,31.959619,0.000,99.000,115.0000,140.0000,197.00,int64
3,BloodPressure,614.0,68.903909,19.933385,0.000,62.000,72.0000,80.0000,114.00,int64
4,SkinThickness,614.0,20.456026,16.063105,0.000,0.000,23.0000,32.0000,99.00,int64
5,Insulin,614.0,81.250814,116.947384,0.000,0.000,27.0000,130.0000,744.00,int64
6,BMI,614.0,31.929642,8.136791,0.000,27.400,32.1500,36.5000,67.10,float64
7,DiabetesPedigreeFunction,614.0,0.468096,0.329203,0.078,0.238,0.3655,0.6285,2.42,float64
8,Age,614.0,33.265472,11.851427,21.000,24.000,29.0000,41.0000,72.00,int64
9,Outcome,614.0,0.342020,0.474773,0.000,0.000,0.0000,1.0000,1.00,int64